# Generated by Django 3.2.14 on 2022-08-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Social Content Type',
                'verbose_name_plural': 'Social Content Types',
            },
        ),
        migrations.AddField(
            model_name='socialcontent',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='content.socialcontenttype', verbose_name='type'),
            preserve_default=False,
        ),
    ]
