# Generated by Django 3.2 on 2022-04-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='mail',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='mail'),
        ),
        migrations.AlterField(
            model_name='usermail',
            name='mail_user',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='mail user'),
        ),
    ]
