# Generated by Django 3.2 on 2022-04-09 23:20

from django.db import migrations, models
import django.db.models.deletion
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_auto_20220406_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail',
            name='plan_enabled',
            field=models.BooleanField(default=True, verbose_name='plan enabled'),
        ),
        migrations.CreateModel(
            name='UserReceivedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_mail', models.CharField(blank=True, default='', max_length=255, verbose_name='origin mail')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='subject')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('text_content', mirage.fields.EncryptedTextField(blank=True, default='')),
                ('html_content', mirage.fields.EncryptedTextField(blank=True, default='')),
                ('raw_mail', mirage.fields.EncryptedTextField()),
                ('delivered', models.BooleanField(default=False, verbose_name='delivered')),
                ('delivered_date', models.DateTimeField(default=None, null=True, verbose_name='delivered date')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received', to='mails.usermail', verbose_name='mail')),
            ],
            options={
                'verbose_name': 'User Received Email',
                'verbose_name_plural': 'User Received Emails',
            },
        ),
    ]
