# Generated by Django 3.2 on 2022-04-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_auto_20220409_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReceivedMailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('received_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mails.userreceivedmail', verbose_name='received mail')),
            ],
            options={
                'verbose_name': 'User Received Email Attachment',
                'verbose_name_plural': 'User Received Emails Attachments',
            },
        ),
    ]
