# Generated by Django 3.2 on 2022-04-17 22:40

from django.db import migrations, models
import mails.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_userreceivedmailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='mail_user',
            field=models.CharField(default='qaaa', max_length=25, validators=[mails.validators.UserMailAliasValidator()], verbose_name='mail user'),
            preserve_default=False,
        ),
    ]
