# Generated by Django 3.2 on 2022-04-17 23:43

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_auto_20220417_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreceivedmail',
            name='html_content',
            field=mirage.fields.EncryptedTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='userreceivedmail',
            name='text_content',
            field=mirage.fields.EncryptedTextField(blank=True, default='', null=True),
        ),
    ]
