# Generated by Django 3.2 on 2022-04-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0009_auto_20220418_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermail',
            name='redirect_to',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='redirect to e-mail'),
        ),
    ]
