version: '3.3'

networks:
  inventare:
    driver: bridge

services:
  db:
    image: postgres:9.5.20-alpine
    container_name: db
    volumes:
      - /postgres:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - tunelator

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - tunelator

  api:
    build:
      context: .
      dockerfile: Dockerfile.tunelator
    container_name: api
    entrypoint: ['./entrypoints/tests/entrypoint.api.sh']
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - tunelator
    depends_on:
      - "db"
    environment:
      - COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}

networks:
  tunelator:
