version: '3.3'

networks:
  inventare:
    driver: bridge

services:
  db:
    image: postgres:9.5.20-alpine
    volumes:
      - /postgres:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - tunelator

  api:
    build: ./tunelator
    entrypoint: ['./entrypoint.api.sh']
    ports:
      - 8000:8000
    networks:
      - tunelator
    depends_on:
      - "db"

  worker:
    build: ./tunelator
    entrypoint: ['./entrypoint.worker.sh']
    networks:
      - tunelator
    volumes:
      - /home:/home
    depends_on:
      - "db"
      - "api"
    
  watcher:
    build: ./tunelator
    entrypoint: ['./entrypoint.watcher.sh']
    networks:
      - tunelator
    volumes:
      - /home:/home
    depends_on:
      - "db"
      - "api"

networks:
  tunelator:
