version: '3.3'

networks:
  inventare:
    driver: bridge

services:
  db:
    image: postgres:9.5.20-alpine
    volumes:
      - /postgres:/var/lib/postgresql/data/
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - tunelator

  redis:
    image: redis:alpine
    volumes:
      - /redis:/data
    networks:
      - tunelator

  api:
    build: .
    entrypoint: ['./entrypoint.api.sh']
    ports:
      - 8000:8000
    networks:
      - tunelator
    depends_on:
      - "db"
      - "redis"

  admin:
    build: .
    entrypoint: ['./entrypoint.admin.sh']
    ports:
      - 8080:8080
    networks:
      - tunelator
    depends_on:
      - "db"
      - "redis"

#  worker:
#    build: .
#    entrypoint: ['./entrypoint.worker.sh']
#    networks:
#      - tunelator
#    depends_on:
#      - "db"
#      - "redis"
#      - "web"

networks:
  tunelator:
