# Generated by Django 3.2 on 2022-04-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20220402_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandisplayfeature',
            options={'ordering': ['the_order'], 'verbose_name': 'plan display feature', 'verbose_name_plural': 'plan display features'},
        ),
        migrations.RenameField(
            model_name='plandisplayfeature',
            old_name='order',
            new_name='the_order',
        ),
    ]
