# Generated by Django 3.2 on 2022-04-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20220402_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='plan is visible'),
        ),
    ]
