# Generated by Django 3.2 on 2022-04-03 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0004_plan_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.IntegerField(default=999, verbose_name='monthly price'),
        ),
        migrations.AddField(
            model_name='plan',
            name='mp_plan_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='mercado pago integration id'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='paid', max_length=10, verbose_name='plan type'),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='approval id')),
                ('status', models.CharField(choices=[('authorized', 'Authorized'), ('paused', 'Paused'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='plans.plan', verbose_name='plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
    ]
