# Generated by Django 3.2 on 2022-04-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_auto_20220403_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfigurationIntegerItem',
            fields=[
                ('planconfigurationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plans.planconfigurationitem')),
                ('value', models.IntegerField(default=0, verbose_name='value')),
            ],
            options={
                'verbose_name': 'plan configuration integer item',
                'verbose_name_plural': 'plan configuration integer items',
            },
            bases=('plans.planconfigurationitem',),
        ),
    ]
