# Generated by Django 3.2 on 2022-04-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_approval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='stripe integration price id'),
        ),
    ]
