# Generated by Django 3.2 on 2022-04-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_auto_20220423_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='stripe customer id'),
        ),
    ]
