# Generated by Django 3.2 on 2022-04-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_remove_plan_mp_plan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['the_order'], 'verbose_name': 'plan', 'verbose_name_plural': 'plans'},
        ),
        migrations.AddField(
            model_name='plan',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
        ),
    ]
