# Generated by Django 3.2 on 2022-04-25 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptioncheckout',
            options={'verbose_name': 'Subscription checkout ID', 'verbose_name_plural': 'Subscription checkouts ID'},
        ),
        migrations.CreateModel(
            name='SubscriptionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(max_length=50, verbose_name='checkout id')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Subscription manager ID',
                'verbose_name_plural': 'Subscription managers ID',
            },
        ),
    ]
