# Generated by Django 3.2 on 2022-04-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userfcmtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFCMToken',
        ),
    ]
