# Generated by Django 3.2 on 2022-05-23 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_userfcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, verbose_name='checkout id')),
                ('used', models.BooleanField(default=False, verbose_name='used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Forgot Password Session',
                'verbose_name_plural': 'Forgot Password Sessions',
            },
        ),
    ]
