# Generated by Django 3.2 on 2022-05-23 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_forgotpasswordsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordsession',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 23, 43, 49, 731069, tzinfo=utc), verbose_name='Valid Until'),
            preserve_default=False,
        ),
    ]
