name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Write secrets to repository
        run: |
          printf "%s\n" "$DEV_ENV_FILE" >> ./tunelator/.env
        shell: bash
        env:
          DEV_ENV_FILE: ${{ secrets.TEST_ENV }}
      - run: docker-compose -f docker-compose.test.yml up --build -d
      - run: yarn test
